import React from 'react';
import {Inter} from 'next/font/google';
import './globals.css'
import ThemeProvider from "@/providers/theme-provider";
import AppLayout from "@/components/layout";
import NextAuthProvider from "@/providers/next-auth-provider";

const inter = Inter({subsets: ['latin']});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({children}: { children: React.ReactNode }) => (
    <html lang="en">
    <body className={inter.className}>
    <NextAuthProvider>
        <ThemeProvider>
            <AppLayout>
                {children}
            </AppLayout>
        </ThemeProvider>
    </NextAuthProvider>
    </body>
    </html>
);

export default RootLayout;